### ISSUE TITLE
Add a screenshot in Readme

### ISSUE THREAD

**Issue by serbrech** [microsoft/azpipelines-kubernetesUI#211]
Please add a screenshot in the Readme, I want to know what I get instantaneously when looking at the docs.

Also, how do you set this up to give it a try?
Thanks!

**Comment by madhuv-msft** [comment]
Please follow readme in this repo [after git clone]
Then follow readme of repo https://github.com/microsoft/azpipelines-kubernetesUI-WebApp

https://github.com/microsoft/azpipelines-kubernetesUI-WebApp repo has a PR to update the instructions on to check modifications made in this repo, please check https://github.com/microsoft/azpipelines-kubernetesUI-WebApp/pull/45

**Comment by madhuv-msft** [comment]
@serbrech please let us know if you need any additional details from us.
