### ISSUE TITLE
accessibility issues in dark mode

### ISSUE THREAD

**Issue by madhuv-msft** [microsoft/azpipelines-kubernetesUI#65]
For a user in devops we can setup darkmode [not Windows default high contrast mode], in that UI is looked the following way

![image](https://user-images.githubusercontent.com/26214977/52191524-1165b280-286b-11e9-8842-12438bfc068b.png)

Keyboard also we should define, one of the issue reported:
Keyboard : When using Tab to navigate it is not moving to the highlighted panel
![image](https://user-images.githubusercontent.com/26214977/52191542-2c382700-286b-11e9-9c61-a72b3a1d29ad.png)

**Comment by rakol-ms** [comment]
![dark_theme_1](https://user-images.githubusercontent.com/45386516/60003966-5a3ace00-9689-11e9-8269-253ae37fdd38.jpg)
![dark_theme_2](https://user-images.githubusercontent.com/45386516/60003973-5c9d2800-9689-11e9-9c68-4a215ff7104d.jpg)
@madhuv-msft The above are the screenshots from latest code. I can no longer reproduce this issue
